controllers:
    prefix: /{_locale}
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'dashboard'
        permanent: true
        keepRequestMethod: true