# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    mapper.dashboard_statistics.total_yearly_earned:
        class: App\Presentation\Mapper\DashboardStatisticMapper\TotalYearlyEarnedDashboardStatisticMapper
        tags: [ 'mapper.dashboard_statistic' ]
    mapper.dashboard_statistics.total_yearly_spend:
        class: App\Presentation\Mapper\DashboardStatisticMapper\TotalYearlySpendDashboardStatisticMapper
        tags: [ 'mapper.dashboard_statistic' ]
    mapper.dashboard_statistics.savings_rate:
        class: App\Presentation\Mapper\DashboardStatisticMapper\SavingsRateDashboardStatisticMapper
        tags: [ 'mapper.dashboard_statistic' ]
    mapper.dashboard_statistics.income_expense_ratio:
        class: App\Presentation\Mapper\DashboardStatisticMapper\IncomeExpenseRatioDashboardStatisticMapper
        tags: [ 'mapper.dashboard_statistic' ]

    mapper.breadcrumb.dashboard.transaction.add:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\Transaction\AddBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]
    mapper.breadcrumb.dashboard.transaction.update:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\Transaction\UpdateBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]
    mapper.breadcrumb.dashboard.transaction.delete:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\Transaction\DeleteBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]
    mapper.breadcrumb.dashboard.account:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\AccountBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]
    mapper.breadcrumb.dashboard.account.update:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\Account\UpdateBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]
    mapper.breadcrumb.dashboard.account.password:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\Account\PasswordBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]
    mapper.breadcrumb.dashboard.account.delete:
        class: App\Presentation\Mapper\BreadcrumbMapper\Dashboard\Account\DeleteBreadcrumbMapper
        tags: [ 'mapper.breadcrumb' ]

    App\Domain\Repository\UserRepositoryInterface:
        class: App\Infrastructure\Doctrine\Repository\UserRepository
    App\Domain\Repository\TransactionRepositoryInterface:
        class: App\Infrastructure\Doctrine\Repository\TransactionRepository
