name: Code Quality Checks

on: ['pull_request']

jobs:
  build-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: mbstring, pdo, pdo_pgsql

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: public/build
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install JS dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

  pest-tests:
    name: Pest (${{ matrix.suite }})
    needs: build-assets
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: symfony_test
        options: >-
          --health-cmd="pg_isready -U symfony"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        suite: [unit, functional, integration]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: mbstring, pdo, pdo_pgsql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set DATABASE_URL env
        run: echo "DATABASE_URL=pgsql://symfony:secret@localhost:5432/symfony_test" >> $GITHUB_ENV

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U symfony; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Prepare test database (optional)
        run: |
          php bin/console doctrine:database:create --env=test || true
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Run Pest Suite
        run: vendor/bin/pest --testsuite=${{ matrix.suite }}

  static-analysis:
    name: PHPStan & PHPCS
    runs-on: ubuntu-latest
    needs: build-assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpstan, phpcs

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHPCS
        run: vendor/bin/phpcs